### ISSUE TITLE
Persist scroll position in result/lists

### ISSUE THREAD

**Issue by moshechaikin** [Sefaria/Sefaria-Mobile#103]
When scrolling through a search result (or list of saved sources for example), after clicking on an item and going back - the page starts scrolling from the top instead of at the location of tapped item.

**Comment by moshechaikin** [comment]
For example, clicking on a saved item and going back to the saved page navigates to the top of saved list instead of back to the current item.

![image](https://github.com/Sefaria/Sefaria-Mobile/assets/6878298/98f01c9c-e37a-44a2-b3a7-2740ca8b3745)

![image](https://github.com/Sefaria/Sefaria-Mobile/assets/6878298/2f277ed9-c2e2-4176-abfd-3fb76b8bc0ec)

**Comment by HadaraRachel** [comment]
Thank you for your feedback @moshechaikin, we will look into this issue. 
For any future bug reports or product feedback please contact us at hello@sefaria.org
