### ISSUE TITLE
Deep linking in the app?

### ISSUE THREAD

**Issue by lukecarbis** [Sefaria/Sefaria-Mobile#104]
Is it possible to deep link to the Sefaria from another app? For example, from an iOS app:

```swift
let url = URL(string:"sefaria://parashat-hashavua")
UIApplication.shared.open(url!)
```

Is there a custom url scheme?

**Comment by nsantacruz** [comment]
Hi @lukecarbis, good question. The Sefaria app (both Android and iOS) don't have custom url schemes. However, they do support the standard https urls that sefaria.org supports. Use the format that is found on the site and it should redirect to the app if it's installed.
