### ISSUE TITLE
פתיחה במיקום לא נכון

### ISSUE THREAD

**Issue by HalelFisherman** [Sefaria/Sefaria-Mobile#126]
כשפותחים את האפליקציה (אנדרואיד) היא אמורה ליפתח במיקום האחרון בו היה המשתמש. אך במקום לפתוח במיקום האחרון, האפליקציה פותחת את הפרשן שהיה פתוח בתחתית המסך. זה לא נוח למשתמשים.
הכי טוב אם האפליקציה הייתה נפתחת באותו מצב בו היא נסגרה (מסך ראשי ובתחתית המסך את הפרשן שהיה פתוח לפני). אך כרגע יהיה מצוין גם אם האפליקציה תפתח במסך הראשי האחרון ולא בפרשן האחרון.
תודה רבה

**Comment by HadaraRachel** [comment]
תודה רבה! לקחנו לתשומת ליבנו
