### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [Sefaria/Sefaria-Mobile#17]
Great to see Sefaria is back! Did you decide on any license for the project? I couldn't find a hint.

**Comment by nsantacruz** [comment]
Just added a license. It's been GPL, but now it's officially listed [here](https://github.com/Sefaria/Sefaria-Mobile#license)

**Comment by IzzySoft** [comment]
Thanks! Will revive it then in my repo. If you could add the `LICENSE` file to the repo root, Github would automatically detect it and show it prominently, btw.

Just wondering: at tag v5.12.6, the APK identifies as 5.12.8 – is that intended?

**Comment by nsantacruz** [comment]
You're right, the version number was a mistake. I've updated it.

**Comment by IzzySoft** [comment]
PS: May I ask if some of the proprietary components could be dropped? Do you e.g. really need 2 analytics frameworks? Dropping Firebase Analytics would probably also get rid of the other Firebase modules. Some users don't feel well with the "snooping providers" (where those data end up). No offense meant, just friendly asking :smiley:

**Comment by nsantacruz** [comment]
Totally fine to ask. Firebase gives us amazing insight into the bugs that are affecting users and has consistently helped up improve the quality of the app. I understand concerns for privacy, but at this point it is an extremely helpful module.

You can feel free to fork the repo and remove the the proprietary components.

**Comment by IzzySoft** [comment]
Hehe… thanks, but I'm no dev, so I can't. What would you think about working with flavors – like one `play` with Firebase etc (to deploy to PlayStore), and one `foss` without (which then might even be eligible for F-Droid.org)? If you'd still wanted some analytics there, maybe [this little list](https://gitlab.com/-/snippets/1896503#acceptable-analytics) can give some inspiration. Certainly not the "woah" the big players can offer – but definitely much privacy the big ones can *not* offer. That way you'd have the best of two worlds (think "olam ha-se" and "olam ha-ba") – and as most users will still stick with Play, no loss in your developer console :wink:

The "woah" could then happen when such a great tool as Sefaria is became available at F-Droid, where the privacy-minded no longer had to struggle with their conscience of the "learning mizwah" contra "self defense/protection" :smiley: As soon as there'd be an eligible flavor, I gladly assist with getting Sefaria listed at F-Droid (disclosure: I'm one of the maintainers there).
