### ISSUE TITLE
Opening Talmud-> Rashi Bug

### ISSUE THREAD

**Issue by MDjavaheri** [Sefaria/Sefaria-Mobile#37]
When opening Rashi as a commentary on a line of Talmud, only the exact connection text opens with a loading icon below it. It stays that way indefinitely unless one pulls down and refreshes the page. Bug has been on Android for years.
<img width="215" alt="image" src="https://user-images.githubusercontent.com/8226037/159145339-b472dc5c-41b4-4fa4-bcd7-6f85c7563a86.png">

**Comment by nsantacruz** [comment]
@MDjavaheri Thanks for reporting! Interesting that this issue doesn't appear when you navigate directly to Rashi. This looks like a real issue. I'm going to create a task to track this on our internal tracking system and close this issue.
