### ISSUE TITLE
Build scraper for armit-hebrew transletion

### ISSUE THREAD

**Issue by chenbaruchchen** [Sefaria/Sefaria-Mobile#85]
I'm currently serching for the best way to implemet rhis feature
I will update when the server will be ready for integration with the mobile app

By the way
Love your job and glad its writen in react-native

**Comment by nsantacruz** [comment]
Hi @chenbaruchchen! Thank you for interest in the project. It sounds like you're proposing a new feature, is that right? If so, you can email hello@sefaria.org to suggest new features or offer an idea for collaboration with our team. Interested to hear what you're working on.

I'm going to close this issue for now.
