### ISSUE TITLE
Ability to choose offline Bible translation

### ISSUE THREAD

**Issue by Serentty** [Sefaria/Sefaria-Mobile#98]
I would prefer to be able to read my chosen translation without internet access. Forgive me if this is already a feature and I just have not figured out how to do it. I have tried to select a translation, delete my offline data, and download it again, but even so when I go offline it reverts to the default translation (RJPS).

Thank you for your time.

**Comment by nsantacruz** [comment]
You are write that this currently isn't possible. We are actually looking how feasible this is since it seems like a useful feature. 

Since this is a feature request, I will close this issue and we will track it internally.
